<?php

namespace TimVhostingBundle\Entity;

/**
 * VideoSuggestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoSuggestRepository extends \Doctrine\ORM\EntityRepository
{
}
