<?php

namespace TimVhostingBundle\Entity;

/**
 * VideoRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRateRepository extends \Doctrine\ORM\EntityRepository
{
}
