services:
#    tim_config.example:
#        class: TimConfigBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    tim_config.event_listener.locale_listener:
        class: TimConfigBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

parameters:
    # example to override authentication listeners
    security.authentication.success_handler.class: TimConfigBundle\Handler\Auth\AuthenticationSuccessHandler
    security.authentication.failure_handler.class: TimConfigBundle\Handler\Auth\AuthenticationFailureHandler