# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #bundles:        []
    #assets:
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        bootstrap_fonts_woff:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.woff'
            output: bundles/timvhosting/fonts/glyphicons-halflings-regular.woff
        bootstrap_fonts_woff2:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.woff2'
            output: bundles/timvhosting/fonts/glyphicons-halflings-regular.woff2
        bootstrap_fonts_ttf:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.ttf'
            output: bundles/timvhosting/fonts/glyphicons-halflings-regular.ttf
        bootstrap_fonts_svg:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.svg'
            output: bundles/timvhosting/fonts/glyphicons-halflings-regular.svg
        bootstrap_fonts_eot:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.eot'
            output: bundles/timvhosting/fonts/glyphicons-halflings-regular.eot
        bootstrap_fonts_woff_public:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.woff'
            output: Resources/public/fonts/glyphicons-halflings-regular.woff
        bootstrap_fonts_woff2_public:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.woff2'
            output: Resources/public/fonts/glyphicons-halflings-regular.woff2
        bootstrap_fonts_ttf_public:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.ttf'
            output: Resources/public/fonts/glyphicons-halflings-regular.ttf
        bootstrap_fonts_svg_public:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.svg'
            output: Resources/public/fonts/glyphicons-halflings-regular.svg
        bootstrap_fonts_eot_public:
            inputs:
                - '@TimVhostingBundle/Resources/public/fonts/glyphicons-halflings-regular.eot'
            output: Resources/public/fonts/glyphicons-halflings-regular.eot
        partial_start:
            inputs:
                - '@TimVhostingBundle/Resources/public/partials/start.html'
            output: partials/start.html
        partial_finish:
            inputs:
                - '@TimVhostingBundle/Resources/public/partials/finish.html'
            output: partials/finish.html
        partial_workout:
            inputs:
                - '@TimVhostingBundle/Resources/public/partials/workout.html'
            output: partials/workout.html
        description_panel:
            inputs:
                - '@TimVhostingBundle/Resources/public/partials/description-panel.html'
            output: partials/description-panel.html
        image_start:
            inputs:
                - '@TimVhostingBundle/Resources/public/images/12MinWorkout/start.png'
            output: images/start.png
        image_jumping_jacks:
            inputs:
                - '@TimVhostingBundle/Resources/public/images/12MinWorkout/JumpingJacks.png'
            output: images/JumpingJacks.png
        image_rest:
            inputs:
                - '@TimVhostingBundle/Resources/public/images/12MinWorkout/rest.png'
            output: images/rest.png
        image_wallsit:
            inputs:
                - '@TimVhostingBundle/Resources/public/images/12MinWorkout/wallsit.png'
            output: images/wallsit.png
        image_finish:
            inputs:
                - '@TimVhostingBundle/Resources/public/images/12MinWorkout/finish.png'
            output: images/finish.png
