symfony_best_practices_test:
    resource: "@SymfonyBestPracticesTestBundle/Resources/config/routing.yml"
    prefix:   /

tim_config:
    resource: "@TimConfigBundle/Resources/config/routing.yml"
    prefix:   /

tim_vhosting:
    resource: "@TimVhostingBundle/Resources/config/routing.yml"
    prefix:   /

tim_vhosting_admin:
    resource: "@TimVhostingBundle/Resources/config/routing_admin.yml"
    prefix:   /
