parameters:
  # my_user_provider.class: danvbe\UserBundle\Security\Core\User\FOSUBUserProvider

services:
  _defaults:
    autowire: true # Automatically injects dependencies in your services
    autoconfigure: true
    public: false
    bind:
    # Nice feature here. Local Binding. Read about it at documentation.

  my_user_provider:
    class: "%hwi_oauth.user.provider.fosub_bridge.class%"
    #this is the place where the properties are passed to the UserProvider - see config.yml
    arguments: ['@fos_user.user_manager',{facebook: facebook_id, google: google_id}]
