fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
    service:
        user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

sonata_user:
    security_acl: false
    manager_type: orm

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER
    title:      Admin
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png

#hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
#    firewall_name: secured_area
#    resource_owners:

hwi_oauth:
    firewall_name: secured_area
    resource_owners:
    #    google:
    #        type:                google
    #        client_id:           "<client_id>"
    #        client_secret:       "<client_secret>"
    #        scope:               "email profile"
    #    github:
    #        type:                github
    #        client_id:           "<client_id>"
    #        client_secret:       "<client_secret>"
    #fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
    #    username_iterations: 30

        # mapping between resource owners (see below) and properties
    #    properties:
    #        google: googleID
    #        github: githubID
