parameters:
    google_api_key: '%env(GOOGLE_API_KEY)%'
    tim_vhosting.feedback.handler.class: App\TimVhostingBundle\Handler\FeedbackHandler
    tim_vhosting.video_suggest.handler.class: App\TimVhostingBundle\Handler\VideoSuggestHandler
    tim_vhosting.google_api.handler.class: App\TimVhostingBundle\Handler\GoogleApiHandler

    tim_vhosting.feedback.class: App\TimVhostingBundle\Entity\Feedback
    tim_vhosting.video_suggest.class: App\TimVhostingBundle\Entity\VideoSuggest

services:
#    tim_vhosting.example:
#        class: TimVhostingBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    tim_vhosting.admin.tags:
        class: App\TimVhostingBundle\Admin\TagsAdmin
        arguments: [~, App\TimVhostingBundle\Entity\Tags, App\TimVhostingBundle:TagsAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tags, icon: '<i class="fa fa-database"></i>' }

    tim_vhosting.admin.video_rate:
        class: App\TimVhostingBundle\Admin\VideoRateAdmin
        arguments: [~, App\TimVhostingBundle\Entity\VideoRate, App\TimVhostingBundle:VideoRateAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: VideoRate }

    tim_vhosting.admin.feedback:
        class: App\TimVhostingBundle\Admin\FeedbackAdmin
        arguments: [~, App\TimVhostingBundle\Entity\Feedback, App\TimVhostingBundle:FeedbackAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Feedback }
        calls:
            - [ setTranslationDomain, [ TimVhostingBundle ] ]

    tim_vhosting.admin.video_suggest:
        class: App\TimVhostingBundle\Admin\VideoSuggestAdmin
        arguments: [~, App\TimVhostingBundle\Entity\VideoSuggest, App\TimVhostingBundle:VideoSuggestAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: VideoSuggest }
        calls:
            - [ setTranslationDomain, [ TimVhostingBundle ] ]

    tim_vhosting.admin.video:
        class: App\TimVhostingBundle\Admin\VideoAdmin
        arguments: [~, App\TimVhostingBundle\Entity\Video, App\TimVhostingBundle:VideoAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Video }
        calls:
            - [ setTranslationDomain, [ TimVhostingBundle ] ]

    tim_vhosting.admin.language:
        class: App\TimVhostingBundle\Admin\LanguageAdmin
        arguments: [~, App\TimVhostingBundle\Entity\Language, App\TimVhostingBundle:LanguageAdmin, '@service_container']
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Language }
        public: true
        calls:
            - [ setTranslationDomain, [ TimVhostingBundle ] ]

#handler
    tim_vhosting.feedback.handler:
        class: '%tim_vhosting.feedback.handler.class%'
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '%tim_vhosting.feedback.class%']
    tim_vhosting.video_suggest.handler:
        class: '%tim_vhosting.video_suggest.handler.class%'
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '%tim_vhosting.video_suggest.class%']

    tim_vhosting.google_api.handler:
        class: '%tim_vhosting.google_api.handler.class%'
        arguments: ['@service_container', '@doctrine.orm.entity_manager']
