sonata_user:
    security_acl: false
    manager_type: orm

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.search_result:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

sonata_admin:
    templates:
        layout: 'TimVhostingBundle:Admin:standard_layout.html.twig'
        list:   'TimVhostingBundle:Admin:list.html.twig'
    security:
        handler: sonata.admin.security.handler.role
        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER
    title:      Admin
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png

#hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
#    firewall_name: secured_area
#    resource_owners: